export const STORAGE_PROVIDERS = {
  LOCAL: "LOCAL",
  YANDEX: "YANDEX",
  GOOGLE_DRIVE: "GOOGLE_DRIVE",
  ONEDRIVE: "ONEDRIVE",
  S3: "S3",
  MINIO: "MINIO",
};

export const IMPLEMENTED_STORAGE_PROVIDERS = [STORAGE_PROVIDERS.LOCAL, STORAGE_PROVIDERS.YANDEX];
